package org.zaberura.constants;

public enum ConversationState {

    MAIN_MENU,
    //MAIN_MENU,

    //branch 1; get currency course
    CURRENCY_INFO_WAITING_FOR_CURRENCY1,
    CURRENCY_INFO_WAITING_FOR_CURRENCY2,
    CURRENCY_INFO_WAITING_FOR_TIME_FRAME,
    CURRENCY_INFO_WAITING_FOR_RESULT,
    CURRENCY_INFO_FINISHED,

    //branch 2; currency calculator
    CURRENCY_CALCULATOR_REQUESTED,
    CALCULATOR_CURRENCY1_ENTERED,
    CALCULATOR_CURRENCY2_ENTERED,
    CALCULATOR_AMOUNT_ENTERED,
    CALCULATOR_FINISHED,

}
